/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_shell_freegee_NativeTask */

#ifndef _Included_edu_shell_freegee_NativeTask
#define _Included_edu_shell_freegee_NativeTask
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_shell_freegee_NativeTask
 * Method:    install_package
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jint JNICALL Java_edu_shell_freegee_NativeTask_action
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
